name: jh_eagles
description: A redesign of the Johnston Heights EagleTime app by Chakorn

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.1.3+6

environment:
  sdk: 3.6.0
  flutter: 3.27.1

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.1
  dynamic_color:
    git:
      url: https://github.com/hasali19/material-foundation-flutter-packages.git
      path: packages/dynamic_color
  easy_image_viewer: ^1.5.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_widget_from_html_core: ^0.15.2
  http: ^1.2.2
  intl: ^0.20.1
  jiffy: ^6.3.2
  package_info_plus: ^8.1.2
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
