name: jh_eagles
description: A redesign of the Johnston Heights EagleTime app by Chakorn

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  cached_network_image: ^3.3.1
  dynamic_color: ^1.7.0
  easy_image_viewer: ^1.4.1
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.0.0
  flutter_widget_from_html_core: ^0.14.11
  http: ^1.2.1
  intl: ^0.19.0
  jiffy: ^6.3.0
  package_info_plus: ^7.0.0
  provider: ^6.0.0
  url_launcher: ^6.2.6
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
